### ISSUE TITLE
MPI Error - Impala

### ISSUE THREAD

**Issue by SethKitchen** [heronsystems/adeptRL#2]
Hi I'm trying to run the example on a cuda cluster - 

I am running 
                      adeptRL/0.1.1
                      glibc/2.14
                      python/3.7.0
                      mpi4py/3.0.0
                      torch-nightly/1.0.0.dev20180929
                      CUDA Version 8.0.61
                      mpicc -v
Using built-in specs.
COLLECT_GCC=/share/apps/gcc/7.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/share/apps/gcc/7.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/share/apps/gcc//7.2.0 --with-gmp=/share/apps/gcc//7.2.0/gmp/ --with-mpfr=/share/apps/gcc//7.2.0/mpfr/ --with-mpc=/share/apps/gcc//7.2.0/mpc/ --disable-multilib
Thread model: posix
gcc version 7.2.0 (GCC)

mpiexec -n 3 python3 -m adept.scripts.impala --env-id BeamRiderNoFrameskip-v4 0 1

gives

[cuda-24-1:02171] *** Process received signal ***
[cuda-24-1:02171] Signal: Segmentation fault (11)
[cuda-24-1:02171] Signal code: Address not mapped (1)
[cuda-24-1:02171] Failing at address: 0x46f

**Comment by benbellheron** [comment]
Seth,
Unfortunately, I'm unable to reproduce this on a fresh install. I've uploaded a docker file to master (meant to be used with nvidia-docker) that's working for me (I'm on Ubuntu 18.04 with Cuda 9.1).

However there are lots of things to try that may help nail down where the problem lies. First, the master branch has a couple changes/fixes for newer versions of NumPy (>1.15) and I've also changed the impala gpu args so that a single gpu (or none) can be used. To install from source use: `python setup.py install` (or develop if you're looking to modify the code). 

All the scripts are housed in the adept/scripts folder. Can you let me know if any of the following works/fails? And the output if it fails?
Local Mode:
`python3 local.py`
If local works then try impala without the gpu on a single machine:
`mpirun -np 3 -H localhost:3 python3 -m mpi4py impala.py --gpu-id -1`
Then with a single gpu (still on one machine):
`mpirun -np 3 -H localhost:3 python3 -m mpi4py impala.py --gpu-id 0`

If all of these work then I'm at a loss for what could be the issue. Do you see output like: "Root variables synced" and then each rank should also print "<rank> variables synced" or does it error before then?

**Comment by SethKitchen** [comment]
Ahh it's probably not your code -- just tried to import torch and it failed -- something there -- will reopen if necessary -- sorry

**Comment by benbellheron** [comment]
Seth, no worries. Looks like it's maybe numpy & blas error? I would recommend using conda (https://www.anaconda.com/download/#linux) if you aren't. It packages numpy with Intel's mkl which is an optimized blas package for Intel cpus (not to mention it's a very nice way to manage python environments).

**Comment by SethKitchen** [comment]
Ok I will try that. Thanks for making this repo by the way! I'm amazed you have already figured out IMPALA! Any way to make a wiki on how to add environments?

**Comment by jtatusko** [comment]
Thanks! More documentation on the to do list

**Comment by benbellheron** [comment]
@SethKitchen, I've created a gitter channel for adept where we can discuss further: https://gitter.im/adeptRL/Lobby

**Comment by SethKitchen** [comment]
Nice I joined -- Sorry it took so long -- finally figured out how to get torch to work on cluster. Now I am running and I get runtime error:

--------------------------------------------------------------------------
[[60717,1],2]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: cuda-24-1

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
SC2 Environment not detected
SC2 Environment not detected
SC2 Environment not detected

                     __           __
          ____ _____/ /__  ____  / /_
         / __ `/ __  / _ \/ __ \/ __/
        / /_/ / /_/ /  __/ /_/ / /_
        \__,_/\__,_/\___/ .___/\__/
                       /_/           
                          v0.2.0dev0 
[cuda-24-1.local:23463] 2 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[cuda-24-1.local:23463] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Root variables synced
1 variables synced
2 variables synced
learning_rate: 0.0007
discount: 0.99
seed: 0
nb_env: 32
max_episode_length: 10000
env_id: BeamRiderNoFrameskip-v4
log_dir: /tmp/adept_logs/
max_train_steps: 10000000.0
nb_top_model: 3
epoch_len: 1000000.0
summary_frequency: 10
tag: 
zscore_norm_env: False
skip_rate: 4
normalize_advantage: False
generalized_advantage_estimation: True
tau: 1.0
exp_length: 20
normalize: True
nb_head: 1
gpu_id: [0]
vision_network: Nature
discrete_network: Identity
network_body: LSTM
agent: ActorCriticVtrace
profile: False
debug: False
max_queue_length: 4
num_rollouts_in_batch: 2
max_dynamic_batch: 0
min_dynamic_batch: 0
host_training_info_interval: 100
use_local_buffers: False
mode_name: IMPALA
Network Parameter Count: 7553354
Traceback (most recent call last):
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 231, in <module>
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 143, in main
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 41, in __init__
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 256, in get_parameter_shapes
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModularNetwork' object has no attribute '_all_buffers'
Traceback (most recent call last):
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 231, in <module>
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 123, in main
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 337, in run
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 370, in learn
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 438, in get_parameter_shapes
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModularNetwork' object has no attribute '_all_buffers'
Traceback (most recent call last):
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/python/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 231, in <module>
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/scripts/impala.py", line 123, in main
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 337, in run
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 370, in learn
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/adeptRL-0.2.0.dev0-py3.7.egg/adept/containers/impala.py", line 438, in get_parameter_shapes
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModularNetwork' object has no attribute '_all_buffers'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60717,1],0]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by SethKitchen** [comment]
I fix this by setting use_local_buffers to True -- what does this do/change?

**Comment by benbellheron** [comment]
Hmm this shouldn't be happening. the _all_buffers() is a method of the pytorch nn.Module which will return the buffers in that module (which hold the batch norm statistics in our use case). With use_local_buffers enabled each worker calculates batch statistics only on their environments. When disabled the batch statistics are calculated by the host (which runs larger batches) and sends to the workers. 

It's possible torch has changed the function name in their dev version. Do you get the same error with this code:
```python
from adept.networks._base import ModularNetwork, NetworkTrunk, NetworkBody, NetworkHead
from adept.networks import FourConv, LSTMBody

nt = NetworkTrunk({'Pixel': FourConv([3,84,84], True)})
nb = LSTMBody(nt.nb_output_channel, 256, True)
nh = NetworkHead(nb.nb_output_channel, {'critic': 1, 'actor': 6})
mn = ModularNetwork(nt, nb, nh)
print(list(mn._all_buffers()))
```

**Comment by SethKitchen** [comment]
Yep!

[sjkyv5@cuda-23-13 ~]$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(list(mn._all_buffers()))
  File "/home/sjkyv5/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModularNetwork' object has no attribute '_all_buffers'
[sjkyv5@cuda-23-13 ~]$

**Comment by benbellheron** [comment]
_all_buffers was renamed to buffers() in this PR https://github.com/pytorch/pytorch/pull/10554 we'll have to update those calls when torch releases a new version. For now you could replace all occurrences to buffers()
